export const SUBSCRIPTION_URL = 'https://www.talloo.com/#plans';
export const EVENT_CATEGORY_CONSTANT = {
  TALLOO: require('../../../talloo/assets/Talloo.png'),
  GOOGLE: require('../../../talloo/assets/ic_google.png'),
  ADD: require('../../../talloo/assets/add.png'),
};
export const IMAGE_CONSTANT = {
  ADD: require('../../assets/add.png'),
  APP_LOGO: require('../../assets/ic_launcher.png'),
};

export const TAB_FOOTER_IMAGE_CONSTANT = {
  EVENT_HOME: require('../../assets/FooterTab/FloatFooter/ic_home.png'),
  EVENT_HOME_SELECTED: require('../../assets/FooterTab/FloatFooter/ic_sel_home.png'),
  CHATS: require('../../assets/FooterTab/FloatFooter/ic_chat.png'),
  CHATS_SELECTED: require('../../assets/FooterTab/FloatFooter/ic_sel_chat.png'),
  ADD_EVENT: require('../../assets/FooterTab/FloatFooter/ic_addevent.png'),
  ADD_EVENT_SELECTED: require('../../assets/FooterTab/FloatFooter/ic_sel_addevent.png'),
  USER_DIRECTORY: require('../../assets/FooterTab/FloatFooter/ic_contacts.png'),
  USER_DIRECTORY_SELECTED: require('../../assets/FooterTab/FloatFooter/ic_sel_contacts.png'),
  CALENDER_EVENT: require('../../assets/FooterTab/FloatFooter/ic_calendar.png'),
  CALENDER_EVENT_GRAY: require('../../assets/FooterTab/FloatFooter/ic_calendar_gray.png'),
  REFERRAL: require('../../assets/FooterTab/FloatFooter/ic_referral.png'),
  FOOTER_BACK: require('../../assets/FooterTab/footer_back.png'),
  FOOTER_EVENT: require('../../assets/FooterTab/footer_event.png'),
  FOOTER_ADD: require('../../assets/FooterTab/footer_add.png'),
  FOOTER_TICKET: require('../../assets/FooterTab/footer_ticket.png'),
  FOOTER_SHARE: require('../../assets/FooterTab/ic_share.png'),
  PROFILE: require('../../assets/FooterTab/FloatFooter/ic_default_profile.png'),
  CALENDAR: require('../../assets/FooterTab/FloatFooter/ic_sel_calendar.png'),
  SETTINGS: require('../../assets/FooterTab/ic_settings.png'),

  ContactList: require('../../assets/MsgEvent/userSolidMod.png'),
  ContactListRed: require('../../assets/MsgEvent/userSolidModRed.png'),
  Messsage: require('../../assets/MsgEvent/commentsSolid.png'),
  MesssageRed: require('../../assets/MsgEvent/commentsSolidRed.png'),
  AddScreen: require('../../assets/MsgEvent/plusSolid.png'),
  AddScreenRed: require('../../assets/MsgEvent/plusSolidRed.png'),
  CalendarSolid: require('../../assets/MsgEvent/calendarSolid.png'),
  CalendarSolidRed: require('../../assets/MsgEvent/calendarSolidRed.png'),
  BarsSolid: require('../../assets/MsgEvent/barsSolid.png'),
  BarsSolidRed: require('../../assets/MsgEvent/barsSolidRed.png'),
  dollarSignSolid: require('../../assets/MsgEvent/dollarSignSolid.png'),
  CommentSolid: require('../../assets/MsgEvent/commentSolid.png'),
  UsersSolid: require('../../assets/MsgEvent/usersSolid.png'),
};

export const NEW_PROFILE_IMG = {
  ANGLE_DOWN: require('../../assets/newProfile/angle_down_light.png'),
  ANGLE_LEFT: require('../../assets/newProfile/angle_left_light.png'),
  ANGLE_RIGHT: require('../../assets/newProfile/angle_right_light.png'),
  ARROW_DOWN: require('../../assets/newProfile/arrow_down_light.png'),
  ARROW_UP: require('../../assets/newProfile/arrow_up_light.png'),
  BELL: require('../../assets/newProfile/bell_light.png'),
  COMMENTS: require('../../assets/newProfile/comments_light.png'),
  DOOR_OPEN: require('../../assets/newProfile/door_open_light.png'),
  ELLIPSIS: require('../../assets/newProfile/ellipsis_h_light.png'),
  ENVELOPE: require('../../assets/newProfile/envelope_light.png'),
  EXTERNAL: require('../../assets/newProfile/external_link_light.png'),
  MAP_MARKER_LIGHT: require('../../assets/newProfile/map_marker_light.png'),
  PENCIL: require('../../assets/newProfile/pencil_light.png'),
  PHONE: require('../../assets/newProfile/phone_light.png'),
  PLUS: require('../../assets/newProfile/plus_light.png'),
  STAR_LIGHT: require('../../assets/newProfile/star_light.png'),
  TIMES_LIGHR: require('../../assets/newProfile/times_light.png'),
}